joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    
    axis_linear:  # orig 1 Left thumb stick vertical
      x: 4
    scale_linear:
      x: 1.5   # orig 0.5
    scale_linear_turbo:
      x: 2.5  # orig 1.0

    axis_angular:  # orig 0 Left thumb stick horizontal
      yaw: 3
    scale_angular:
      yaw: 1.5  # orig 0.5
    scale_angular_turbo:
      yaw: 3.5  # orig 1.0

    require_enable_button: true
    enable_button: 4  # Left shoulder button, 4, originally 6
    enable_turbo_button: 5  # Right shoulder button, 5, originally 7

